/**
 * NSE Index Directory & Constituents Catalog
 * Contains categorized directory of official NSE indices and their constituent symbols.
 */

export const NSE_INDEX_CATEGORIES = [
  {
    category: '📈 Broad Market Indices',
    indices: [
      { id: 'NIFTY 50', name: 'NIFTY 50', description: 'Top 50 Large-Cap Bluechips' },
      { id: 'NIFTY NEXT 50', name: 'NIFTY NEXT 50', description: 'Next 50 Large-Cap Growth Leaders' },
      { id: 'NIFTY 100', name: 'NIFTY 100', description: 'Top 100 Large-Cap Companies' },
      { id: 'NIFTY 200', name: 'NIFTY 200', description: 'Top 200 Market Leaders' },
      { id: 'NIFTY 500', name: 'NIFTY 500', description: 'Top 500 Companies (Broad Market)' },
      { id: 'NIFTY MIDCAP 50', name: 'NIFTY MIDCAP 50', description: 'Top 50 High-Growth Midcaps' },
      { id: 'NIFTY MIDCAP 100', name: 'NIFTY MIDCAP 100', description: 'Top 100 Liquid Midcaps' },
      { id: 'NIFTY MIDCAP 150', name: 'NIFTY MIDCAP 150', description: 'All 150 Midcap Companies' },
      { id: 'NIFTY SMALLCAP 50', name: 'NIFTY SMALLCAP 50', description: 'Top 50 High-Momentum Smallcaps' },
      { id: 'NIFTY SMALLCAP 100', name: 'NIFTY SMALLCAP 100', description: 'Top 100 Liquid Smallcaps' },
      { id: 'NIFTY SMALLCAP 250', name: 'NIFTY SMALLCAP 250', description: 'All 250 Smallcap Companies' },
      { id: 'NIFTY MICROCAP 250', name: 'NIFTY MICROCAP 250', description: 'High-Potential Microcaps' },
      { id: 'NIFTY TOTAL MARKET', name: 'NIFTY TOTAL MARKET', description: 'Entire Indian Stock Market' },
    ],
  },
  {
    category: '🏦 Sectoral Indices',
    indices: [
      { id: 'NIFTY BANK', name: 'NIFTY BANK', description: 'Top 12 Banking Heavyweights' },
      { id: 'NIFTY PSU BANK', name: 'NIFTY PSU BANK', description: 'State-Owned PSU Banks' },
      { id: 'NIFTY PRIVATE BANK', name: 'NIFTY PRIVATE BANK', description: 'Private Commercial Banks' },
      { id: 'NIFTY FINANCIAL SERVICES', name: 'NIFTY FINANCIAL SERVICES', description: 'Banks, NBFCs, Insurance' },
      { id: 'NIFTY IT', name: 'NIFTY IT', description: 'Information Technology Leaders' },
      { id: 'NIFTY AUTO', name: 'NIFTY AUTO', description: 'Automobile & EV Manufacturers' },
      { id: 'NIFTY PHARMA', name: 'NIFTY PHARMA', description: 'Pharmaceutical & Drug Makers' },
      { id: 'NIFTY HEALTHCARE INDEX', name: 'NIFTY HEALTHCARE', description: 'Hospitals, Labs & Healthcare' },
      { id: 'NIFTY METAL', name: 'NIFTY METAL', description: 'Steel, Aluminum & Mining' },
      { id: 'NIFTY ENERGY', name: 'NIFTY ENERGY', description: 'Oil, Gas & Power Utilities' },
      { id: 'NIFTY OIL & GAS', name: 'NIFTY OIL & GAS', description: 'Upstream & Downstream Energy' },
      { id: 'NIFTY FMCG', name: 'NIFTY FMCG', description: 'Fast Moving Consumer Goods' },
      { id: 'NIFTY REALTY', name: 'NIFTY REALTY', description: 'Real Estate & Property Developers' },
      { id: 'NIFTY MEDIA', name: 'NIFTY MEDIA', description: 'Broadcasting & Entertainment' },
      { id: 'NIFTY CONSUMER DURABLES', name: 'NIFTY CONSUMER DURABLES', description: 'Electronics, Appliances & Home' },
    ],
  },
  {
    category: '🚀 Thematic & Strategy Indices',
    indices: [
      { id: 'NIFTY INDIA DEFENCE', name: 'NIFTY DEFENCE', description: 'Defense, Aerospace & Shipbuilders' },
      { id: 'NIFTY INDIA RAILWAYS PSU', name: 'NIFTY RAILWAYS PSU', description: 'Rail Infrastructure & PSUs' },
      { id: 'NIFTY EV & NEW AGE AUTOMOTIVE', name: 'NIFTY EV & NEW AGE AUTO', description: 'Electric Vehicles & Clean Tech' },
      { id: 'NIFTY MOBILITY', name: 'NIFTY MOBILITY', description: 'Logistics, Transport & Aviation' },
      { id: 'NIFTY INFRASTRUCTURE', name: 'NIFTY INFRASTRUCTURE', description: 'Construction, Power & Ports' },
      { id: 'NIFTY CPSE', name: 'NIFTY CPSE', description: 'Central Public Sector Enterprises' },
      { id: 'NIFTY PSE', name: 'NIFTY PSE', description: 'Public Sector Enterprises' },
      { id: 'NIFTY MNC', name: 'NIFTY MNC', description: 'Multinational Corporations' },
      { id: 'NIFTY INDIA TOURISM', name: 'NIFTY TOURISM', description: 'Hotels, Travel & Aviation' },
      { id: 'NIFTY CHEMICALS', name: 'NIFTY CHEMICALS', description: 'Specialty & Agro Chemicals' },
      { id: 'NIFTY CAPITAL MARKETS', name: 'NIFTY CAPITAL MARKETS', description: 'Brokers, Exchanges & AMCs' },
      { id: 'NIFTY COMMODITIES', name: 'NIFTY COMMODITIES', description: 'Metals, Oil & Raw Materials' },
      { id: 'NIFTY SERVICES SECTOR', name: 'NIFTY SERVICES SECTOR', description: 'Telecom, IT & Financial Services' },
      { id: 'NIFTY INDIA DIGITAL', name: 'NIFTY DIGITAL', description: 'Internet, Fintech & Software' },
      { id: 'NIFTY INDIA MANUFACTURING', name: 'NIFTY MANUFACTURING', description: 'Industrial & Make in India' },
    ],
  },
];

export const INDEX_CONSTITUENTS_MAP = {
  'NIFTY 50': [
    { symbol: 'RELIANCE', companyName: 'Reliance Industries Ltd', sector: 'Energy / Oil & Gas' },
    { symbol: 'TCS', companyName: 'Tata Consultancy Services Ltd', sector: 'Information Technology' },
    { symbol: 'HDFCBANK', companyName: 'HDFC Bank Ltd', sector: 'Banking & Financials' },
    { symbol: 'INFY', companyName: 'Infosys Ltd', sector: 'Information Technology' },
    { symbol: 'ICICIBANK', companyName: 'ICICI Bank Ltd', sector: 'Banking & Financials' },
    { symbol: 'BHARTIARTL', companyName: 'Bharti Airtel Ltd', sector: 'Telecommunication' },
    { symbol: 'SBIN', companyName: 'State Bank of India', sector: 'Banking & Financials' },
    { symbol: 'ITC', companyName: 'ITC Ltd', sector: 'FMCG / Tobacco' },
    { symbol: 'LT', companyName: 'Larsen & Toubro Ltd', sector: 'Infrastructure / Capital Goods' },
    { symbol: 'BAJFINANCE', companyName: 'Bajaj Finance Ltd', sector: 'Financial Services' },
    { symbol: 'TATAMOTORS', companyName: 'Tata Motors Ltd', sector: 'Automobile' },
    { symbol: 'M&M', companyName: 'Mahindra & Mahindra Ltd', sector: 'Automobile' },
    { symbol: 'SUNPHARMA', companyName: 'Sun Pharmaceutical Industries Ltd', sector: 'Healthcare & Pharma' },
    { symbol: 'TITAN', companyName: 'Titan Company Ltd', sector: 'Consumer Discretionary' },
    { symbol: 'MARUTI', companyName: 'Maruti Suzuki India Ltd', sector: 'Automobile' },
    { symbol: 'KOTAKBANK', companyName: 'Kotak Mahindra Bank Ltd', sector: 'Banking & Financials' },
    { symbol: 'AXISBANK', companyName: 'Axis Bank Ltd', sector: 'Banking & Financials' },
    { symbol: 'NTPC', companyName: 'NTPC Ltd', sector: 'Utilities & Power' },
    { symbol: 'ONGC', companyName: 'Oil & Natural Gas Corporation Ltd', sector: 'Energy / Oil & Gas' },
    { symbol: 'POWERGRID', companyName: 'Power Grid Corporation of India Ltd', sector: 'Utilities & Power' },
    { symbol: 'ADANIENT', companyName: 'Adani Enterprises Ltd', sector: 'Conglomerate' },
    { symbol: 'ADANIPORTS', companyName: 'Adani Ports & Special Economic Zone Ltd', sector: 'Infrastructure' },
    { symbol: 'TATASTEEL', companyName: 'Tata Steel Ltd', sector: 'Metals & Mining' },
    { symbol: 'COALINDIA', companyName: 'Coal India Ltd', sector: 'Energy & Mining' },
    { symbol: 'ULTRACEMCO', companyName: 'UltraTech Cement Ltd', sector: 'Cement' },
    { symbol: 'HINDALCO', companyName: 'Hindalco Industries Ltd', sector: 'Metals & Mining' },
    { symbol: 'JSWSTEEL', companyName: 'JSW Steel Ltd', sector: 'Metals & Mining' },
    { symbol: 'NESTLEIND', companyName: 'Nestle India Ltd', sector: 'FMCG / Food' },
    { symbol: 'GRASIM', companyName: 'Grasim Industries Ltd', sector: 'Materials & Chemicals' },
    { symbol: 'TECHM', companyName: 'Tech Mahindra Ltd', sector: 'Information Technology' },
    { symbol: 'WIPRO', companyName: 'Wipro Ltd', sector: 'Information Technology' },
    { symbol: 'HCLTECH', companyName: 'HCL Technologies Ltd', sector: 'Information Technology' },
    { symbol: 'BAJAJFINSV', companyName: 'Bajaj Finserv Ltd', sector: 'Financial Services' },
    { symbol: 'EICHERMOT', companyName: 'Eicher Motors Ltd', sector: 'Automobile' },
    { symbol: 'DRREDDY', companyName: "Dr. Reddy's Laboratories Ltd", sector: 'Healthcare & Pharma' },
    { symbol: 'CIPLA', companyName: 'Cipla Ltd', sector: 'Healthcare & Pharma' },
    { symbol: 'DIVISLAB', companyName: "Divi's Laboratories Ltd", sector: 'Healthcare & Pharma' },
    { symbol: 'APOLLOHOSP', companyName: 'Apollo Hospitals Enterprise Ltd', sector: 'Healthcare' },
    { symbol: 'HEROMOTOCO', companyName: 'Hero MotoCorp Ltd', sector: 'Automobile' },
    { symbol: 'TRENT', companyName: 'Trent Ltd', sector: 'Retail & Consumer' },
    { symbol: 'BEL', companyName: 'Bharat Electronics Ltd', sector: 'Defense & Aerospace' },
    { symbol: 'BPCL', companyName: 'Bharat Petroleum Corporation Ltd', sector: 'Energy' },
    { symbol: 'SHRIRAMFIN', companyName: 'Shriram Finance Ltd', sector: 'Financial Services' },
    { symbol: 'INDUSINDBK', companyName: 'IndusInd Bank Ltd', sector: 'Banking' },
    { symbol: 'BRITANNIA', companyName: 'Britannia Industries Ltd', sector: 'FMCG / Food' },
    { symbol: 'ASIANPAINT', companyName: 'Asian Paints Ltd', sector: 'Paints & Coatings' },
    { symbol: 'TATACONSUM', companyName: 'Tata Consumer Products Ltd', sector: 'FMCG / Food' },
    { symbol: 'SBILIFE', companyName: 'SBI Life Insurance Company Ltd', sector: 'Insurance' },
    { symbol: 'HDFCLIFE', companyName: 'HDFC Life Insurance Company Ltd', sector: 'Insurance' },
    { symbol: 'BAJAJ-AUTO', companyName: 'Bajaj Auto Ltd', sector: 'Automobile' },
  ],

  'NIFTY BANK': [
    { symbol: 'HDFCBANK', companyName: 'HDFC Bank Ltd', sector: 'Private Bank' },
    { symbol: 'ICICIBANK', companyName: 'ICICI Bank Ltd', sector: 'Private Bank' },
    { symbol: 'SBIN', companyName: 'State Bank of India', sector: 'PSU Bank' },
    { symbol: 'KOTAKBANK', companyName: 'Kotak Mahindra Bank Ltd', sector: 'Private Bank' },
    { symbol: 'AXISBANK', companyName: 'Axis Bank Ltd', sector: 'Private Bank' },
    { symbol: 'INDUSINDBK', companyName: 'IndusInd Bank Ltd', sector: 'Private Bank' },
    { symbol: 'BANKBARODA', companyName: 'Bank of Baroda', sector: 'PSU Bank' },
    { symbol: 'PNB', companyName: 'Punjab National Bank', sector: 'PSU Bank' },
    { symbol: 'FEDERALBNK', companyName: 'Federal Bank Ltd', sector: 'Private Bank' },
    { symbol: 'IDFCFIRSTB', companyName: 'IDFC First Bank Ltd', sector: 'Private Bank' },
    { symbol: 'AUBANK', companyName: 'AU Small Finance Bank Ltd', sector: 'Private Bank' },
    { symbol: 'BANDHANBNK', companyName: 'Bandhan Bank Ltd', sector: 'Private Bank' },
  ],

  'NIFTY IT': [
    { symbol: 'TCS', companyName: 'Tata Consultancy Services Ltd', sector: 'IT Services' },
    { symbol: 'INFY', companyName: 'Infosys Ltd', sector: 'IT Services' },
    { symbol: 'HCLTECH', companyName: 'HCL Technologies Ltd', sector: 'IT Services' },
    { symbol: 'WIPRO', companyName: 'Wipro Ltd', sector: 'IT Services' },
    { symbol: 'TECHM', companyName: 'Tech Mahindra Ltd', sector: 'IT Services' },
    { symbol: 'LTIM', companyName: 'LTIMindtree Ltd', sector: 'IT Services' },
    { symbol: 'PERSISTENT', companyName: 'Persistent Systems Ltd', sector: 'IT Software' },
    { symbol: 'COFORGE', companyName: 'Coforge Ltd', sector: 'IT Services' },
    { symbol: 'MPHASIS', companyName: 'Mphasis Ltd', sector: 'IT Services' },
    { symbol: 'LTTS', companyName: 'L&T Technology Services Ltd', sector: 'Engineering ER&D' },
  ],

  'NIFTY AUTO': [
    { symbol: 'MARUTI', companyName: 'Maruti Suzuki India Ltd', sector: 'Passenger Vehicles' },
    { symbol: 'TATAMOTORS', companyName: 'Tata Motors Ltd', sector: 'Commercial & EVs' },
    { symbol: 'M&M', companyName: 'Mahindra & Mahindra Ltd', sector: 'SUVs & Tractors' },
    { symbol: 'BAJAJ-AUTO', companyName: 'Bajaj Auto Ltd', sector: 'Two & Three Wheelers' },
    { symbol: 'EICHERMOT', companyName: 'Eicher Motors Ltd', sector: 'Royal Enfield / CVs' },
    { symbol: 'HEROMOTOCO', companyName: 'Hero MotoCorp Ltd', sector: 'Two Wheelers' },
    { symbol: 'TVSMOTOR', companyName: 'TVS Motor Company Ltd', sector: 'Two Wheelers' },
    { symbol: 'BHARATFORG', companyName: 'Bharat Forge Ltd', sector: 'Auto Ancillaries' },
    { symbol: 'BOSCHLTD', companyName: 'Bosch Ltd', sector: 'Auto Components' },
    { symbol: 'SAMVARDHANA', companyName: 'Samvardhana Motherson International Ltd', sector: 'Wiring & Components' },
    { symbol: 'ASHOKLEY', companyName: 'Ashok Leyland Ltd', sector: 'Commercial Vehicles' },
    { symbol: 'MRF', companyName: 'MRF Ltd', sector: 'Tyres & Rubber' },
    { symbol: 'APOLLOTYRE', companyName: 'Apollo Tyres Ltd', sector: 'Tyres & Rubber' },
    { symbol: 'BALKRISIND', companyName: 'Balkrishna Industries Ltd', sector: 'Off-Highway Tyres' },
    { symbol: 'SONACOMS', companyName: 'Sona BLW Precision Forgings Ltd', sector: 'EV Components' },
  ],

  'NIFTY NEXT 50': [
    { symbol: 'HAL', companyName: 'Hindustan Aeronautics Ltd', sector: 'Defense' },
    { symbol: 'VBL', companyName: 'Varun Beverages Ltd', sector: 'Beverages' },
    { symbol: 'ZOMATO', companyName: 'Zomato Ltd', sector: 'Online Food / Quick Commerce' },
    { symbol: 'JIOFIN', companyName: 'Jio Financial Services Ltd', sector: 'Financials' },
    { symbol: 'DLF', companyName: 'DLF Ltd', sector: 'Realty' },
    { symbol: 'SIEMENS', companyName: 'Siemens Ltd', sector: 'Capital Goods' },
    { symbol: 'ABB', companyName: 'ABB India Ltd', sector: 'Industrial Automation' },
    { symbol: 'IOC', companyName: 'Indian Oil Corporation Ltd', sector: 'Oil Refining' },
    { symbol: 'GAIL', companyName: 'GAIL (India) Ltd', sector: 'Natural Gas' },
    { symbol: 'CHOLAFIN', companyName: 'Cholamandalam Investment and Finance Co Ltd', sector: 'NBFC' },
    { symbol: 'VEDL', companyName: 'Vedanta Ltd', sector: 'Diversified Metals' },
    { symbol: 'INDIGO', companyName: 'InterGlobe Aviation Ltd', sector: 'Airlines' },
    { symbol: 'HAVELLS', companyName: 'Havells India Ltd', sector: 'Consumer Electricals' },
    { symbol: 'PFC', companyName: 'Power Finance Corporation Ltd', sector: 'Power NBFC' },
    { symbol: 'RECLTD', companyName: 'REC Ltd', sector: 'Power NBFC' },
    { symbol: 'BANKBARODA', companyName: 'Bank of Baroda', sector: 'PSU Bank' },
    { symbol: 'PNB', companyName: 'Punjab National Bank', sector: 'PSU Bank' },
    { symbol: 'TVSMOTOR', companyName: 'TVS Motor Company Ltd', sector: 'Automobile' },
    { symbol: 'AMBUJACEM', companyName: 'Ambuja Cements Ltd', sector: 'Cement' },
    { symbol: 'CANBK', companyName: 'Canara Bank', sector: 'PSU Bank' },
  ],

  'NIFTY INDIA DEFENCE': [
    { symbol: 'HAL', companyName: 'Hindustan Aeronautics Ltd', sector: 'Fighter Jets & Helicopters' },
    { symbol: 'BEL', companyName: 'Bharat Electronics Ltd', sector: 'Radars & Defense Electronics' },
    { symbol: 'MAZDOCK', companyName: 'Mazagon Dock Shipbuilders Ltd', sector: 'Submarines & Warships' },
    { symbol: 'COCHINSHIP', companyName: 'Cochin Shipyard Ltd', sector: 'Aircraft Carriers & Ships' },
    { symbol: 'BDL', companyName: 'Bharat Dynamics Ltd', sector: 'Missiles & Torpedoes' },
    { symbol: 'GRSE', companyName: 'Garden Reach Shipbuilders & Engineers Ltd', sector: 'Warships & Frigates' },
    { symbol: 'BEML', companyName: 'BEML Ltd', sector: 'Defense & Heavy Rail' },
    { symbol: 'PARAS', companyName: 'Paras Defence and Space Tech Ltd', sector: 'Defense Optics & Space' },
    { symbol: 'DATAPATTNS', companyName: 'Data Patterns (India) Ltd', sector: 'Defense Avionics' },
    { symbol: 'MTARTECH', companyName: 'MTAR Technologies Ltd', sector: 'Clean Energy & Defense' },
    { symbol: 'ASTRAMICRO', companyName: 'Astra Microwave Products Ltd', sector: 'Radar & EW Systems' },
    { symbol: 'DYNAMATECH', companyName: 'Dynamatic Technologies Ltd', sector: 'Aerospace Structures' },
    { symbol: 'ZENITEC', companyName: 'Zen Technologies Ltd', sector: 'Anti-Drone & Simulators' },
  ],

  'NIFTY INDIA RAILWAYS PSU': [
    { symbol: 'IRFC', companyName: 'Indian Railway Finance Corporation Ltd', sector: 'Railway NBFC' },
    { symbol: 'RVNL', companyName: 'Rail Vikas Nigam Ltd', sector: 'Rail Infrastructure' },
    { symbol: 'IRCTC', companyName: 'Indian Railway Catering and Tourism Corp Ltd', sector: 'Ticketing & Catering' },
    { symbol: 'IRCON', companyName: 'Ircon International Ltd', sector: 'Rail EPC & Turnkey' },
    { symbol: 'RITES', companyName: 'RITES Ltd', sector: 'Railway Consultancy & Exports' },
    { symbol: 'RAILTEL', companyName: 'RailTel Corporation of India Ltd', sector: 'Telecom & Rail Broadband' },
    { symbol: 'TITAGARH', companyName: 'Titagarh Rail Systems Ltd', sector: 'Vande Bharat Trains & Wagons' },
    { symbol: 'JWL', companyName: 'Jupiter Wagons Ltd', sector: 'Wagons & Braking Systems' },
    { symbol: 'TEXRAIL', companyName: 'Texmaco Rail & Engineering Ltd', sector: 'Wagons & Track EPC' },
    { symbol: 'BEML', companyName: 'BEML Ltd', sector: 'Metro Coaches & Rolling Stock' },
  ],

  'NIFTY MIDCAP 100': [
    { symbol: 'SUZLON', companyName: 'Suzlon Energy Ltd', sector: 'Renewable Wind Energy' },
    { symbol: 'PRESTIGE', companyName: 'Prestige Estates Projects Ltd', sector: 'Realty' },
    { symbol: 'PERSISTENT', companyName: 'Persistent Systems Ltd', sector: 'IT' },
    { symbol: 'COCHINSHIP', companyName: 'Cochin Shipyard Ltd', sector: 'Shipbuilding' },
    { symbol: 'MAZDOCK', companyName: 'Mazagon Dock Shipbuilders Ltd', sector: 'Defense' },
    { symbol: 'FEDERALBNK', companyName: 'Federal Bank Ltd', sector: 'Banking' },
    { symbol: 'OBEROIRLTY', companyName: 'Oberoi Realty Ltd', sector: 'Real Estate' },
    { symbol: 'DIXON', companyName: 'Dixon Technologies (India) Ltd', sector: 'Electronics EMS' },
    { symbol: 'POLYCAB', companyName: 'Polycab India Ltd', sector: 'Wires & Cables' },
    { symbol: 'KAYNES', companyName: 'Kaynes Technology India Ltd', sector: 'EMS & Semiconductors' },
    { symbol: 'TATACOMM', companyName: 'Tata Communications Ltd', sector: 'Telecom' },
    { symbol: 'VOLTAS', companyName: 'Voltas Ltd', sector: 'Consumer Appliances' },
    { symbol: 'PHOENIXLTD', companyName: 'The Phoenix Mills Ltd', sector: 'Malls & Commercial Real Estate' },
    { symbol: 'AUROPHARMA', companyName: 'Aurobindo Pharma Ltd', sector: 'Pharma' },
    { symbol: 'LUPIN', companyName: 'Lupin Ltd', sector: 'Pharma' },
    { symbol: 'ASHOKLEY', companyName: 'Ashok Leyland Ltd', sector: 'Commercial Vehicles' },
    { symbol: 'CUMMINSIND', companyName: 'Cummins India Ltd', sector: 'Engines & Power Gensets' },
    { symbol: 'BHARATFORG', companyName: 'Bharat Forge Ltd', sector: 'Forgings & Defense' },
    { symbol: 'GODREJPROP', companyName: 'Godrej Properties Ltd', sector: 'Real Estate' },
    { symbol: 'MPHASIS', companyName: 'Mphasis Ltd', sector: 'IT Services' },
  ],

  'NIFTY SMALLCAP 100': [
    { symbol: 'WEL', companyName: 'Wonder Electricals Ltd', sector: 'Consumer Electronics & Fans' },
    { symbol: 'GENCON', companyName: 'Generic Engineering Construction & Projects Ltd', sector: 'Construction & EPC' },
    { symbol: 'KAYNES', companyName: 'Kaynes Technology India Ltd', sector: 'Electronics Manufacturing' },
    { symbol: 'CDSL', companyName: 'Central Depository Services (India) Ltd', sector: 'Capital Markets' },
    { symbol: 'BSE', companyName: 'BSE Ltd', sector: 'Stock Exchange' },
    { symbol: 'MCX', companyName: 'Multi Commodity Exchange of India Ltd', sector: 'Commodity Exchange' },
    { symbol: 'ANANTRAJ', companyName: 'Anant Raj Ltd', sector: 'Real Estate & Data Centers' },
    { symbol: 'RADICO', companyName: 'Radico Khaitan Ltd', sector: 'Breweries & Distilleries' },
    { symbol: 'AMBER', companyName: 'Amber Enterprises India Ltd', sector: 'AC Components & EMS' },
    { symbol: 'MANAPPURAM', companyName: 'Manappuram Finance Ltd', sector: 'Gold NBFC' },
    { symbol: 'PVRINOX', companyName: 'PVR INOX Ltd', sector: 'Cinema Exhibition' },
    { symbol: 'CAMS', companyName: 'Computer Age Management Services Ltd', sector: 'Mutual Fund RTA' },
    { symbol: 'ANGELONE', companyName: 'Angel One Ltd', sector: 'Fintech & Broking' },
    { symbol: 'CENTURYTEX', companyName: 'Century Textiles and Industries Ltd', sector: 'Real Estate & Paper' },
    { symbol: 'JBCHEPHARM', companyName: 'J.B. Chemicals & Pharmaceuticals Ltd', sector: 'Pharma' },
    { symbol: 'SONATSOFTW', companyName: 'Sonata Software Ltd', sector: 'IT Software' },
    { symbol: 'ZENSARTECH', companyName: 'Zensar Technologies Ltd', sector: 'IT Services' },
    { symbol: 'CYIENT', companyName: 'Cyient Ltd', sector: 'Engineering & Technology' },
  ],

  'NIFTY PHARMA': [
    { symbol: 'SUNPHARMA', companyName: 'Sun Pharmaceutical Industries Ltd', sector: 'Pharma' },
    { symbol: 'DRREDDY', companyName: "Dr. Reddy's Laboratories Ltd", sector: 'Pharma' },
    { symbol: 'CIPLA', companyName: 'Cipla Ltd', sector: 'Pharma' },
    { symbol: 'DIVISLAB', companyName: "Divi's Laboratories Ltd", sector: 'APIs & CRAMS' },
    { symbol: 'LUPIN', companyName: 'Lupin Ltd', sector: 'Pharma' },
    { symbol: 'AUROPHARMA', companyName: 'Aurobindo Pharma Ltd', sector: 'Pharma' },
    { symbol: 'TORNTPHARM', companyName: 'Torrent Pharmaceuticals Ltd', sector: 'Pharma' },
    { symbol: 'ZYDUSLIFE', companyName: 'Zydus Lifesciences Ltd', sector: 'Pharma' },
    { symbol: 'ALKEM', companyName: 'Alkem Laboratories Ltd', sector: 'Pharma' },
    { symbol: 'MANKIND', companyName: 'Mankind Pharma Ltd', sector: 'Pharma & OTC' },
    { symbol: 'GLENMARK', companyName: 'Glenmark Pharmaceuticals Ltd', sector: 'Pharma' },
    { symbol: 'BIOCON', companyName: 'Biocon Ltd', sector: 'Biologics' },
    { symbol: 'LAURUSLABS', companyName: 'Laurus Labs Ltd', sector: 'Pharma & APIs' },
    { symbol: 'IPCALAB', companyName: 'IPCA Laboratories Ltd', sector: 'Pharma' },
    { symbol: 'GLAND', companyName: 'Gland Pharma Ltd', sector: 'Injectables' },
  ],

  'NIFTY METAL': [
    { symbol: 'TATASTEEL', companyName: 'Tata Steel Ltd', sector: 'Steel' },
    { symbol: 'JSWSTEEL', companyName: 'JSW Steel Ltd', sector: 'Steel' },
    { symbol: 'HINDALCO', companyName: 'Hindalco Industries Ltd', sector: 'Aluminum & Copper' },
    { symbol: 'VEDL', companyName: 'Vedanta Ltd', sector: 'Mining & Multi-Metals' },
    { symbol: 'JINDALSTEL', companyName: 'Jindal Steel & Power Ltd', sector: 'Steel & Power' },
    { symbol: 'COALINDIA', companyName: 'Coal India Ltd', sector: 'Coal Mining' },
    { symbol: 'NMDC', companyName: 'NMDC Ltd', sector: 'Iron Ore Mining' },
    { symbol: 'SAIL', companyName: 'Steel Authority of India Ltd', sector: 'Steel' },
    { symbol: 'NATIONALUM', companyName: 'National Aluminium Co Ltd', sector: 'Aluminum' },
    { symbol: 'APLAPOLLO', companyName: 'APL Apollo Tubes Ltd', sector: 'Structural Steel Tubes' },
    { symbol: 'RATNAMANI', companyName: 'Ratnamani Metals & Tubes Ltd', sector: 'Pipes & Tubes' },
    { symbol: 'HINDZINC', companyName: 'Hindustan Zinc Ltd', sector: 'Zinc, Lead & Silver' },
    { symbol: 'WELCORP', companyName: 'Welspun Corp Ltd', sector: 'Line Pipes' },
  ],

  'NIFTY REALTY': [
    { symbol: 'DLF', companyName: 'DLF Ltd', sector: 'Residential & Commercial' },
    { symbol: 'GODREJPROP', companyName: 'Godrej Properties Ltd', sector: 'Residential Real Estate' },
    { symbol: 'OBEROIRLTY', companyName: 'Oberoi Realty Ltd', sector: 'Luxury Housing' },
    { symbol: 'PRESTIGE', companyName: 'Prestige Estates Projects Ltd', sector: 'Real Estate' },
    { symbol: 'PHOENIXLTD', companyName: 'The Phoenix Mills Ltd', sector: 'Retail Malls & Commercial' },
    { symbol: 'BRIGADE', companyName: 'Brigade Enterprises Ltd', sector: 'Real Estate & Hospitality' },
    { symbol: 'SOBHA', companyName: 'Sobha Ltd', sector: 'Luxury Real Estate' },
    { symbol: 'SIGNATURE', companyName: 'Signatureglobal (India) Ltd', sector: 'Affordable & Mid Housing' },
    { symbol: 'MAHLIFE', companyName: 'Mahindra Lifespace Developers Ltd', sector: 'Real Estate & Industrial' },
    { symbol: 'SUNTECK', companyName: 'Sunteck Realty Ltd', sector: 'Luxury Housing' },
  ],

  'NIFTY ENERGY': [
    { symbol: 'RELIANCE', companyName: 'Reliance Industries Ltd', sector: 'Oil & Gas' },
    { symbol: 'NTPC', companyName: 'NTPC Ltd', sector: 'Power Generation' },
    { symbol: 'POWERGRID', companyName: 'Power Grid Corporation of India Ltd', sector: 'Power Transmission' },
    { symbol: 'ONGC', companyName: 'Oil & Natural Gas Corporation Ltd', sector: 'Oil Exploration' },
    { symbol: 'BPCL', companyName: 'Bharat Petroleum Corporation Ltd', sector: 'Oil Refining' },
    { symbol: 'IOC', companyName: 'Indian Oil Corporation Ltd', sector: 'Oil Refining' },
    { symbol: 'COALINDIA', companyName: 'Coal India Ltd', sector: 'Coal Mining' },
    { symbol: 'TATAPOWER', companyName: 'Tata Power Company Ltd', sector: 'Solar, Wind & Thermal' },
    { symbol: 'ADANIGREEN', companyName: 'Adani Green Energy Ltd', sector: 'Renewable Energy' },
    { symbol: 'ADANIPOWER', companyName: 'Adani Power Ltd', sector: 'Thermal Power' },
    { symbol: 'GAIL', companyName: 'GAIL (India) Ltd', sector: 'Gas Transmission' },
  ],
};

export function getConstituentsForIndex(indexId = 'NIFTY 50') {
  const normalized = String(indexId || 'NIFTY 50').trim().toUpperCase();
  if (INDEX_CONSTITUENTS_MAP[normalized]) {
    return INDEX_CONSTITUENTS_MAP[normalized];
  }

  // Check aliases or default to NIFTY 50
  const match = Object.keys(INDEX_CONSTITUENTS_MAP).find(
    (k) => k.toUpperCase().replace(/\s+/g, '') === normalized.replace(/\s+/g, '')
  );
  if (match) {
    return INDEX_CONSTITUENTS_MAP[match];
  }

  return INDEX_CONSTITUENTS_MAP['NIFTY 50'];
}

