const apiKey = `eyJraWQiOiJaTUtjVXciLCJhbGciOiJFUzI1NiJ9.eyJleHAiOjI1NzYxMjAxMjQsImlhdCI6MTc4NzcyMDEyNCwibmJmIjoxNzg3NzIwMTI0LCJzdWIiOiJ7XCJ0b2tlblJlZklkXCI6XCJmY2M1Njc3Yi1lOTQ2LTQ0MzctYWVlMS0yOGFkNDJlMGUyM2NcIixcInZlbmRvckludGVncmF0aW9uS2V5XCI6XCJlMzFmZjIzYjA4NmI0MDZjODg3NGIyZjZkODQ5NTMxM1wiLFwidXNlckFjY291bnRJZFwiOlwiZjgzOWE2YzItNjc3NS00ZmJmLTlmMTYtZGQyNDAwMjUyZmI4XCIsXCJkZXZpY2VJZFwiOlwiZDBhNTY0NDktNGZhNS01NTlkLTgyYTktMTVjNTNkZWY1ZTgwXCIsXCJzZXNzaW9uSWRcIjpcIjgwOTVkMjU2LTljMmMtNGNjMi04NDI1LWZiYTI1ZDcwZTk2NVwiLFwiYWRkaXRpb25hbERhdGFcIjpcIno1NC9NZzltdjE2WXdmb0gvS0EwYkRnVTVOdVpKZE1ka2R2RUNHWWw2ZlJSTkczdTlLa2pWZDNoWjU1ZStNZERhWXBOVi9UOUxIRmtQejFFQisybTdRPT1cIixcInJvbGVcIjpcImF1dGgtdG90cFwiLFwic291cmNlSXBBZGRyZXNzXCI6XCIyNDA2OmI0MDA6YjE6ZTNlNzplZDRkOmQ1OWQ6YmM1ODplMDM1LDE3Mi42OS4xNzguMjAsMzUuMjQxLjIzLjEyM1wiLFwidHdvRmFFeHBpcnlUc1wiOjI1NzYxMjAxMjQ1ODEsXCJ2ZW5kb3JOYW1lXCI6XCJncm93d0FwaVwifSIsImlzcyI6ImFwZXgtYXV0aC1wcm9kLWFwcCJ9.sX0RhFt-Rn3y7aH_scWDe999NkTi71PiTdhImqWty-kQciBJkCcTS6fdxT9L5hcWnQOYg0l5rW_mTEN63rj4PQ`;

const parts = apiKey.split('.');
const payload = JSON.parse(Buffer.from(parts[1], 'base64').toString('utf8'));
console.log('JWT header:', JSON.parse(Buffer.from(parts[0], 'base64').toString('utf8')));
console.log('JWT payload:', payload);
if (payload.sub) {
  console.log('JWT sub parsed:', JSON.parse(payload.sub));
}

